"use client";

import { DashboardLayout } from "@/components/layout/dashboard-layout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { 
  Area, 
  AreaChart, 
  ResponsiveContainer, 
  Tooltip, 
  XAxis, 
  YAxis, 
  Bar, 
  BarChart, 
  CartesianGrid,
  Legend
} from "recharts";
import { 
  Activity, 
  TrendingUp, 
  Clock, 
  Milestone, 
  ArrowUpRight, 
  Zap,
  Calendar
} from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

const data = [
  { day: "Mon", planned: 5, actual: 4.8 },
  { day: "Tue", planned: 8, actual: 8.2 },
  { day: "Wed", planned: 0, actual: 0 },
  { day: "Thu", planned: 12, actual: 11.5 },
  { day: "Fri", planned: 6, actual: 7.0 },
  { day: "Sat", planned: 22, actual: 22.4 },
  { day: "Sun", planned: 0, actual: 0 },
];

const stats = [
  { label: "Weekly Mileage", value: "53.9 mi", change: "+4.2%", icon: Milestone },
  { label: "Current VDOT", value: "54.2", change: "+0.8", icon: Zap },
  { label: "Avg Heart Rate", value: "142 bpm", change: "-2.1%", icon: Activity },
  { label: "Recovery Score", value: "88%", change: "Optimal", icon: Clock },
];

export default function Home() {
  return (
    <DashboardLayout>
      <div className="space-y-8 animate-in fade-in duration-500">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          {stats.map((stat) => (
            <Card key={stat.label} className="bg-card border-border hover:border-accent/50 transition-colors shadow-sm">
              <CardHeader className="flex flex-row items-center justify-between pb-2 space-y-0">
                <CardTitle className="text-sm font-medium text-muted-foreground">
                  {stat.label}
                </CardTitle>
                <stat.icon className="h-4 w-4 text-accent" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-headline font-bold">{stat.value}</div>
                <p className={cn(
                  "text-xs mt-1 flex items-center",
                  stat.change.startsWith("+") ? "text-accent" : "text-muted-foreground"
                )}>
                  {stat.change}
                  <ArrowUpRight className="ml-1 h-3 w-3" />
                </p>
              </CardContent>
            </Card>
          ))}
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <Card className="lg:col-span-2 bg-card border-border shadow-md">
            <CardHeader>
              <div className="flex items-center justify-between">
                <div>
                  <CardTitle className="font-headline">Volume Comparison</CardTitle>
                  <CardDescription>Planned vs. Realized weekly mileage (miles)</CardDescription>
                </div>
                <Badge variant="outline" className="text-accent border-accent/20 bg-accent/5">Current Week</Badge>
              </div>
            </CardHeader>
            <CardContent>
              <div className="h-[300px] w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <AreaChart data={data}>
                    <defs>
                      <linearGradient id="colorActual" x1="0" y1="0" x2="0" y2="1">
                        <stop offset="5%" stopColor="hsl(var(--accent))" stopOpacity={0.3}/>
                        <stop offset="95%" stopColor="hsl(var(--accent))" stopOpacity={0}/>
                      </linearGradient>
                    </defs>
                    <XAxis dataKey="day" stroke="hsl(var(--muted-foreground))" fontSize={12} tickLine={false} axisLine={false} />
                    <YAxis stroke="hsl(var(--muted-foreground))" fontSize={12} tickLine={false} axisLine={false} />
                    <Tooltip 
                      contentStyle={{ backgroundColor: 'hsl(var(--card))', borderColor: 'hsl(var(--border))', borderRadius: '0.5rem' }}
                      itemStyle={{ color: 'hsl(var(--foreground))' }}
                    />
                    <Area type="monotone" dataKey="actual" stroke="hsl(var(--accent))" fillOpacity={1} fill="url(#colorActual)" strokeWidth={2} />
                    <Area type="monotone" dataKey="planned" stroke="hsl(var(--muted-foreground))" strokeDasharray="5 5" fill="transparent" strokeWidth={1} />
                  </AreaChart>
                </ResponsiveContainer>
              </div>
            </CardContent>
          </Card>

          <Card className="bg-card border-border shadow-md">
            <CardHeader>
              <CardTitle className="font-headline">Next Training Session</CardTitle>
              <CardDescription>Generated by AI Periodization Engine</CardDescription>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="p-4 rounded-xl bg-secondary/50 border border-border space-y-3">
                <div className="flex items-center gap-2 text-accent font-semibold">
                  <Calendar className="size-4" />
                  <span>Thursday, Oct 24</span>
                </div>
                <h3 className="font-headline text-lg font-bold">Tempo Intervals</h3>
                <p className="text-sm text-muted-foreground leading-relaxed">
                  2mi Warm-up @ Zone 1-2. Main: 3 x 2mi @ T-Pace (6:45/mi) with 2:00 jog recovery. 1mi Cool-down.
                </p>
                <div className="pt-2">
                  <Badge variant="secondary" className="bg-primary/20 text-primary-foreground border-primary/30">Construction Phase</Badge>
                </div>
              </div>
              <div className="space-y-2">
                <div className="flex justify-between text-sm">
                  <span className="text-muted-foreground">Block Progress</span>
                  <span className="font-medium">Week 2 of 4</span>
                </div>
                <div className="w-full h-2 bg-secondary rounded-full overflow-hidden">
                  <div className="h-full bg-accent w-[45%]" />
                </div>
              </div>
              <Button className="w-full bg-primary hover:bg-primary/90">View Full Plan</Button>
            </CardContent>
          </Card>
        </div>
      </div>
    </DashboardLayout>
  );
}

import { cn } from "@/lib/utils";
